# how to uses
# turn on this file and uncomment serverless config in deploy_lambda.yml workflows

service: compress-image

provider:
  name: aws
  runtime: nodejs16.x
  stage: prod
  region: ap-southeast-1

functions:
  _:
    handler: index.handler
