name: Deploy lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        function-name: ["arn:aws:lambda:ap-southeast-1:581617270143:function:compress-image-prod-_"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}


      - name: Install dependencies
        run: npm install --platform=linux --arch=x64 sharp

      - name: Install dependencies2
        run: npm install --save-dev @types/node

      - name: Build
        run: npm run build

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: zip Lambda Function
        run: |
          zip -r lambda_function_payload.zip .
      - name: AWS Deploy
        run: |
          aws lambda update-function-code --function-name ${{ matrix.function-name }} --zip-file fileb://lambda_function_payload.zip